// This is where project configuration and plugin options are located. 
// Learn more: https://gridsome.org/docs/config

// Changes here require a server restart.
// To restart press CTRL + C in terminal and run `gridsome develop`

module.exports = {
  siteName: 'Generated by GridSome, Netlify, Github, MicroCMS',
  siteUrl: 'https://codehack.dev',
  plugins: [
    '~/plugins/fontawesome.js',
    {
      use: '@gridsome/plugin-sitemap',
      options: {
        cacheTime: 600000, // default
        exclude: [],
        config: {
          '/works/*': {
            changefreq: 'weekly',
            priority: 0.8
          },
        }
      }
    },
    {
      use: '@gridsome/plugin-google-analytics',
      options: {
        id: 'UA-180707313-1'
      }
    }
  ],
  templates: {
    Works: [
      {
        path: '/works/:path',
        component: './src/templates/WorksPost.vue'
      }
    ]
  }
}
