// This is where project configuration and plugin options are located. 
// Learn more: https://gridsome.org/docs/config

// Changes here require a server restart.
// To restart press CTRL + C in terminal and run `gridsome develop`

module.exports = {
  siteName: 'Generated by GridSome, Netlify, Github, MicroCMS',
  // siteUrl: '/',
  plugins: [],
  templates: {
    Works: [
      {
        // path: (node) => {
        //   return `/works/${node.path}/`
        // },
        path: '/works/:path',
        component: './src/templates/WorksPost.vue'
      }
    ]
  }
}
